### ISSUE TITLE
test_redo

### ISSUE THREAD

**Issue by halnader** [ApplyBoard/coop-fall-2020-challenge#157]
Does not test simple undo redo as explained in video. https://youtu.be/X6NJkWbM1xk?t=219
Once stepped back in time should not be able to redo.

Test fails when it assumes redo should result in output of 11, but instead gets 6.

0 -> (add 5) 5 -> (add 5) 10 -> (add 5) 15 -> (undo) 10 -> (undo) 5 -> (add 1) 6 *future erased, no redo

**Comment by Vishesh-Gupta** [comment]
Well the problem here is the way it is in the test cases. You are correct though as the usual mechanics is you shouldn't have the state of redo once you have something done after some undo steps as the state branches off. This is a much more complicated thing to implement in the time frame since more states need to be managed and hence this behavior was used for the challenge

I am not sure but that is my opinion and idea about it. @omasabdullah can maybe confirm or deny this

**Comment by tjuqxb** [comment]
I think you are right.
